ARG BASE_IMAGE=gcr.io/distroless/python3-debian11:debug
#ARG BASE_IMAGE=gcr.io/distroless/python3-debian11
FROM ${BASE_IMAGE}

WORKDIR /app

COPY . .

ENV PATH="venv/bin:$PATH"
ENV FLASK_APP=run.py
ENV PYTHONPATH=venv/lib/python3.9/site-packages

ENTRYPOINT ["python3"]
CMD ["-m", "flask", "run", "--host=0.0.0.0", "--port=5000"]
