ARG BASE_IMAGE=gcr.io/distroless/python3-debian11:debug
FROM ${BASE_IMAGE}

USER nonroot
WORKDIR /home/nonroot

COPY . .

ENV PATH="venv/bin:$PATH"
ENV FLASK_APP=run.py

ENTRYPOINT ["python3"]
CMD ["-m", "flask", "run", "--host=0.0.0.0", "--port=5000"]
