FROM ghcr.io/codepraxis-io/debian11:python3-build as build

WORKDIR /home/devsecops

COPY requirements.txt requirements.txt

RUN python3 -m venv venv
ENV PATH="venv/bin:$PATH"

# this will use the pip in the virtualenv
RUN pip3 install --disable-pip-version-check -r requirements.txt

#FROM gcr.io/distroless/python3-debian11:debug
FROM gcr.io/distroless/python3-debian11:nonroot

WORKDIR /app

COPY . .
COPY --from=build /home/devsecops/venv venv

ENV PATH="venv/bin:$PATH"
ENV FLASK_APP=run.py
ENV PYTHONPATH=venv/lib/python3.9/site-packages

ENTRYPOINT ["venv/bin/python3"]
CMD ["-m", "flask", "run", "--host=0.0.0.0", "--port=5000"]

